# CURSO DE PYTHON - UDEMY
# EXEMPLO DE ARQUIVO .GITIGNORE PARA IGNORAR ARQUIVOS ESPECÍFICOS
# AUTOR:CLAUDEMIR PEDROSO CUBAS

curso = "Python Udemy"
print("Bem-vindo ao curso de", curso)

# EXEMPLO DE CÓDIGO SIMPLES
print